/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ariskourt.lambda;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.ariskourt.lambda.models.MigrationRequest;
import com.ariskourt.lambda.models.MigrationResult;
import com.ariskourt.lambda.services.FlywayMigrationService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@RequiredArgsConstructor
public class LambdaSchemaMigrator implements RequestHandler<MigrationRequest, MigrationResult> {

    private final FlywayMigrationService migrationService;

    public LambdaSchemaMigrator() {
        this(FlywayMigrationService.getInstance());
    }

    @Override
    public MigrationResult handleRequest(MigrationRequest input, Context context) {
	return migrationService.migrate(input.getBucketName());
    }

}
